[Output]
Format=disk
ImageId=juno
ManifestFormat=json
Output=%i_%v_%a
SplitArtifacts=uki,partitions

[Content]
Bootable=yes
RootPassword=hashed:$6$V4bf/bJS/AffGLns$yXmOzf0UU2rijWJoVzLOgIwZmZAu7A9PUVoi8.uSKkvGIry55xRSYAgsAPD0CaPxJy5tY4yviRutFZhPRYpn00
UnifiedKernelImageFormat=%i_%v_%a
Packages=
        acl
        attr
        bash-completion
        bpftool
        btrfs-progs
        ca-certificates
        console-data
        coreutils
        cpio
        cryptsetup-bin
        curl
        dbus-broker
        debian-archive-keyring
        diffutils
        dmidecode
        dosfstools
        e2fsprogs
        efibootmgr
        erofs-utils
        exfatprogs
        fdisk
        fido2-tools
        file
        findutils
        fish
        fwupd
        gdb
        gdisk
        git
        git-lfs
        grep
        gzip
        iproute2
        iputils-ping
        iw
        jq
        kbd
        kexec-tools
        kmod
        less
        libcap-ng-utils
        libidn2-0
        libmtp-runtime
        libnss-myhostname
        libnss-mymachines
        libnss-systemd
        libpam-pwquality
        libpam-systemd
        libpwquality1
        libqrencode4
        linux-image-generic
        linux-perf
        linux-sysctl-defaults
        login
        man
        manpages
        mtools
        nano
        nftables
        nvme-cli
        opensc
        openssh-client
        openssh-server
        openssl
        p11-kit
        passwd
        patch
        pciutils
        pcsc-tools
        pcscd
        pkcs11-provider
        polkitd
        procps
        python3
        rsync
        sbsigntool
        sed
        socat
        systemd
        systemd-boot
        systemd-boot-efi
        systemd-boot-efi-signed
        systemd-container
        systemd-coredump
        systemd-cryptsetup
        systemd-homed
        systemd-repart
        systemd-resolved
        systemd-sysv
        systemd-timesyncd
        systemd-ukify
        systemd-zram-generator
        tar
        tpm2-tools
        tree
        udev
        unzip
        usbutils
        util-linux
        util-linux-extra
        wget
        which
        xxd
        xz-utils
        zip
Autologin=yes

[Config]
Dependencies=initrd