[Build]
CacheDirectory=mkosi.cache
History=yes
ToolsTree=yes
Incremental=yes

[Distribution]
Distribution=debian
Release=trixie
Snapshot=20260516T022736Z
Repositories=non-free-firmware

[Output]
OutputDirectory=mkosi.output
Format=none

[Content]
SourceDateEpoch=0

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4
Ephemeral=yes
QemuArgs=-blockdev driver=raw,node-name=juno-disk,discard=unmap,file.driver=file,file.filename=mkosi.output/juno_%v_%a.raw
         -device nvme,drive=juno-disk,serial=juno,bootindex=0

[Validation]
Verity=auto
SecureBoot=no
