[Partition]
CopyFiles=/etc:/@/etc
CopyFiles=/usr:/@/usr
CopyFiles=/usr.erofs:/@usr
Format=btrfs
Label=ROOT
Type=root
SizeMinBytes=5G
SizeMaxBytes=10G
Subvolumes=/@ /@usr:nodatacow
MakeDirectories=/@ /@/.usr /@/boot /@/dev /@/etc /@/home /@/mnt /@/root /@/tmp /@/usr /@/var /@usr
DefaultSubvolume=/@