[Partition]
CopyFiles=/etc:/@/etc
CopyFiles=/@images:/@images
Format=btrfs
Compression=zstd
CompressionLevel=1
Label=ROOT
Type=root
SizeMinBytes=5G
Subvolumes=/@ /@images:nodatacow
MakeDirectories=/@ /@/boot /@/dev /@/etc /@/home /@/mnt /@/root /@/tmp /@/usr /@/var /@images
DefaultSubvolume=/@
Encrypt=key-file